version: "3.5"
services:
  db:
    container_name: mongodb-dentist # Container name
    image: mongo # image name to start/build
    ports: # Port mapping
      - "27017:27017"
    volumes: # Volume binding
      - "c:/data/db:/data/db"
  spring-WebAPI: # The name of the service
    build:
      context: . # Location of Dockerfile
      dockerfile: Dockerfile
    container_name: dentist-spring-WebAPI
    image: dentist-spring-webapi:dev
    depends_on: # start after
      - db
    ports:
      - "8080:8080"
    links: # list mapping: service_name:name_how_will_see_your_program
      - "db:mymongo"
