version: "3.5"
services:
  angular-WebUI:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dentist-angular-webui
    image: dentist-angular-webui:dev.1
    ports:
      - "80:80"