version: "3.5"
services:
  main-db:
    container_name: mongodb-dentist # Container name
    image: mongo # image name to start/build
    ports: # Port mapping
      - 27017:27017
    volumes: # Volume binding
      - "c:/data/db:/data/db"
  cache-db:
    container_name: dentist-redis
    image: redis
    ports:
      - 6379:6379
    volumes:
      - "c:/data/redis/data:/data"
  spring-WebAPI: # The name of the service
    build:
      context: . # Location of Dockerfile
      dockerfile: Dockerfile
    container_name: dentist-spring-WebAPI
    image: dentist-spring-webapi:dev
    depends_on: # start after
      - main-db
      - cache-db
    ports:
      - 8080:8080
    links: # list mapping: service_name:name_how_will_see_your_program
      - main-db
