version: "3.5"
services:
  spring-WebAPI: # The name of the service
    build:
      context: . # Location of Dockerfile
      dockerfile: Dockerfile
    container_name: dentist-spring-WebAPI
    image: dentist-spring-webapi:dev
    depends_on: # start after
      - main-db
      - cache-db
    ports:
      - 8080:8080
    volumes:
      - "./img_db/:/img_db"
    links: # list mapping: service_name:name_how_will_see_your_program
      - main-db
      - cache-db
